### ISSUE TITLE
保健所選択画面が必要

### ISSUE THREAD

**Issue by halsk** [codeforjapan/remote-patient-monitoring-dashboard#130]
Nurse アカウントが複数の保健所に所属する形でAPIを作ってしまったので、ログイン→保健所選択→患者表示の流れにする必要がある。

`/centers` ページを作り、保健所を選択できるようにする。

**Comment by kaizumaki** [comment]
@halsk おお、そうなのですね。figmaで作ってくれたらこちらで引き取ります！
@MakoMizuno 保健所選択ページ、figmaでモック作成いかがでしょう？

**Comment by MakoMizuno** [comment]
@kaizumaki 保健所選択を追加しますね！
@halsk ユーザーの流れですが、ログイン時に保健所を選択するのはいかがですか？ログインと保健所選択は別ページとして扱った方がいいでしょうか？

**Comment by halsk** [comment]
確かに、それが良さそうです！> 保健所選択をログイン時に

**Comment by MakoMizuno** [comment]
@kaizumaki @halsk ログイン画面に保健所の選択を追加したので、確認をお願いします！
https://www.figma.com/file/29X7k8bKfFlWS6Md5BhrME/%E9%81%A0%E9%9A%94%E7%99%82%E9%A4%8A%E8%80%85%E3%83%A2%E3%83%8B%E3%82%BF%E3%83%AA%E3%83%B3%E3%82%B0%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0?node-id=4053%3A109

**Comment by kaizumaki** [comment]
@MakoMizuno ありがとうございます！
ふと気づいたのですが、保健師は自分の所属している保健所の中から選択したほうがいいような。
そうすると、いったんログイン処理が必要になってきます。

ログイン処理 -> 自分の所属している保健所一覧表示 -> 保健所選択

このあたりどうなんでしょう？ @halsk 
（せっかくfigma整えてもらったのにすみません 🙇‍♀️ ）
