### ISSUE TITLE
患者登録時に呼び出すAPIで、sendSMS フラグを付ける

### ISSUE THREAD

**Issue by halsk** [codeforjapan/remote-patient-monitoring-dashboard#221]
テストデータを登録する時にSMSが飛ぶとややこしいので、明示的に sendSMS パラメータが true の場合のみ、SMSを送信するようにしました。患者登録時にこのフラグを入れるようにしてもらえますでしょうか。

![image](https://user-images.githubusercontent.com/16509/111652292-516d3100-884a-11eb-8f43-29d52cc0be8e.png)

**Comment by kaizumaki** [comment]
対応します！
