### ISSUE TITLE
本番は本番用のAPIを呼び出す

### ISSUE THREAD

**Issue by halsk** [codeforjapan/remote-patient-monitoring-dashboard#231]
本番でも staging を呼んでいるので修正の必要あり

**Comment by halsk** [comment]
#232 で .env ファイルを作ったが、変わらないようだ？？

**Comment by Nekoya3** [comment]
stagingの環境ではAPIの読み先をCodePipeline側で上書きしています

**Comment by halsk** [comment]
Production 側では GitHub Actions を使っているのですが、CodePipeline 側の処理を確認してみます

**Comment by halsk** [comment]
あー。.env じゃなくて環境変数を変えれば良いのか

**Comment by halsk** [comment]
#240 で修正
