### ISSUE TITLE
保健所を一度選択した後、サイドバーから「保健所を選択」を選ぶと、Page Not Found となってしまう

### ISSUE THREAD

**Issue by halsk** [codeforjapan/remote-patient-monitoring-dashboard#260]
一度保健所を選択した後に、サイドバーから「保健所を選択」をすると Page Not Found になる

![](https://i.gyazo.com/890eb6e6d558462af7df3733c284acf0.gif)

**Comment by kaizumaki** [comment]
こちら対応します！
