### ISSUE TITLE
新規患者登録じのログインURLに#がついていない

### ISSUE THREAD

**Issue by halsk** [codeforjapan/remote-patient-monitoring-dashboard#339]
患者の新規登録をしたときにログインURLがコピーできるが、hash モードになっていない。
![image](https://user-images.githubusercontent.com/16509/121798421-38b1c300-cc61-11eb-9966-8ee393ce909c.png)

`https://client.stgrms.stopcovid19.jp/login/323073cb-d4d2-...`

のようになっているが、正しくは

`https://client.stgrms.stopcovid19.jp/#/login/323073cb-d4d2-...`

となるべき

**Comment by kaizumaki** [comment]
@halsk こちらですが、envで設定したいのですが、いかがでしょう？ref. #295

**Comment by halsk** [comment]
あ、なるほど。見てみます

**Comment by halsk** [comment]
AWS側のCode buildの設定で修正しました！ありがとうございました。
